* ping

diff --git a/backupdb b/backupdb
--- a/backupdb
+++ b/backupdb
@@ -37,11 +37,16 @@ fi
 mkdir -p /app/$fecha
 
 while read -r ip puerto usuario clave db; do
-	echo "$ip", "$puerto", "$usuario", "$clave", "$db"
-	verori=$(PGPASSWORD=$clave psql -h $ip -p $puerto -U $usuario -d $db -c 'show server_version;' | grep -v '(1 row)' | grep -v 'server_version' | sed 1d | sed 2d | cut -c 1-6)
-	echo "version: $verori"
-	PGPASSWORD="$clave" pg_dump -Fc -h $ip -p $puerto -U $usuario -d $db > /app/$fecha/$db-$ip-$puerto.dump
-	echo "==================="
+	echo "$ip", "$puerto", "$db", "$usuario", "$clave"
+	ping -A -c 5 $ip > /dev/null
+	if [[ $? = 0 ]]; then
+		verori=$(PGPASSWORD=$clave psql -h $ip -p $puerto -U $usuario -d $db -c 'show server_version;' | grep -v '(1 row)' | grep -v 'server_version' | sed 1d | sed 2d | cut -c 1-6)
+		echo "version: $verori"
+		PGPASSWORD="$clave" pg_dump -Fc -h $ip -p $puerto -U $usuario -d $db > /app/$fecha/$db-$ip-$puerto.dump
+		echo "==================="
+	else
+		echo "ERROR: $ip no esta disponible."
+	fi
 done < ./lista.txt
 
 echo "duracion $SECONDS segundos"
diff --git a/comparardb b/comparardb
--- a/comparardb
+++ b/comparardb
@@ -71,6 +71,21 @@ if [[ -z "$PASS2" ]]; then
 fi
 
 clear
+ping -A -c 5 $IP1 > /dev/null
+if [[ $? = 0 ]]; then
+	echo "$IP1 esta disponible."
+else
+	echo "ERROR: $IP1 no esta disponible."
+	exit 1
+fi
+
+ping -A -c 5 $IP2 > /dev/null
+if [[ $? = 0 ]]; then
+	echo "$IP2 esta disponible."
+else
+	echo "ERROR: $IP2 no esta disponible."
+	exit 1
+fi
 
 contarori=$(PGPASSWORD=$PASS1 psql -h $IP1 -p $PORT1 -U $USER1 -d $DBNAME -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'" | grep -v '(1 row)' | sed 1d | sed 1d | sed 2d)
 contardes=$(PGPASSWORD=$PASS2 psql -h $IP2 -p $PORT2 -U $USER2 -d $DBNAME -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'" | grep -v '(1 row)' | sed 1d | sed 1d | sed 2d)
diff --git a/copiardb b/copiardb
--- a/copiardb
+++ b/copiardb
@@ -70,6 +70,22 @@ fi
 
 rm -f /app/*.dump
 clear
+ping -A -c 5 $IP1 > /dev/null
+if [[ $? = 0 ]]; then
+	echo "$IP1 esta disponible."
+else
+	echo "ERROR: $IP1 no esta disponible."
+	exit 1
+fi
+
+ping -A -c 5 $IP2 > /dev/null
+if [[ $? = 0 ]]; then
+	echo "$IP2 esta disponible."
+else
+	echo "ERROR: $IP2 no esta disponible."
+	exit 1
+fi
+
 echo "backup"
 verori=$(PGPASSWORD=$PASS1 psql -h $IP1 -p $PORT1 -U $USER1 -d $DBNAME -c 'show server_version;' | grep -v '(1 row)' | grep -v 'server_version' | sed 1d | sed 2d | cut -c 1-6)
 echo "Version: $verori"
